kernel:
  image: linuxkit/kernel:5.10.92
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:8f1e6a0747acbbb4d7e24dc98f97faa8d1c6cec7
  - linuxkit/runc:f01b88c7033180d50ae43562d72707c6881904e4
  - linuxkit/containerd:de1b18eed76a266baa3092e5c154c84f595e56da
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
  - linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:bdc99eeedc224439ff237990ee06e5b992c8c1ae
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: modprobe
    image: linuxkit/modprobe:1b59b4f2ebb877085ea0d8d3a41cf06f64c09a15
    command: ["modprobe", "kvm_intel"]
  - name: ip
    image: linuxkit/ip:6cc44dd4e18ddb02de01bc4b34b5799971b6a7bf
    binds:
     - /etc/ip:/etc/ip
    command: ["ip", "-b", "/etc/ip/tap0.conf"]
services:
  #- name: getty
  #  image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
  #  env:
  #   - INSECURE=true
  #   - CONTAINERD_NAMESPACE=services.linuxkit
  - name: solo5
    image: linuxkit/solo5:e1863083744015052785919f476a47fec6bc9048
    command: ["/sbin/solo5-hvt", "--net:service=tap0", "/unikernel.hvt"]
    binds.add:
    - /unikernel.hvt:/unikernel.hvt

files:
  - path: etc/linuxkit-config
    metadata: yaml
  - path: /unikernel.hvt
    source: "www.hvt"
  - path: etc/ip/tap0.conf
    contents: |
      tuntap add tap0 mode tap
      link set tap0 up
